Algoritmo "ExemploVetores"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/04/2024
Var
// Seção de Declarações das variáveis 
 v:vetor [0..3} de real
 i:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo